// src/components/tv/Focusable.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { getFocusContext } from '@/lib/spatial/spatialContext';
  import { spatialNav, generateFocusKey, type SpatialNavParams } from '@/lib/spatial/spatialAction';

  interface Props {
    focusKey?: string;
    parentFocusKey?: string;
    onEnterPress?: (details?: any) => void;
    onArrowPress?: (direction: string, details: any) => boolean;
    onFocus?: () => void;
    onBlur?: () => void;
    autoFocus?: boolean;
    trackChildren?: boolean;
    saveLastFocusedChild?: boolean;
    preferredChildFocusKey?: string;
    focusable?: boolean;
    tabIndex?: number;
    playSound?: boolean;
    isFocusBoundary?: boolean;
    class?: string;
    focusedClass?: string;
    role?: string;
    id?: string;
    children?: Snippet<[{ focused: boolean }]> | Snippet;
  }

  let {
    focusKey = generateFocusKey(),
    parentFocusKey,
    onEnterPress,
    onArrowPress,
    onFocus,
    onBlur,
    autoFocus = false,
    trackChildren = false,
    saveLastFocusedChild = false,
    preferredChildFocusKey,
    focusable = true,
    tabIndex = 0,
    playSound = true,
    isFocusBoundary = false,
    class: className = '',
    focusedClass = '',
    role = 'button',
    id,
    children,
  }: Props = $props();

  let isFocused = $state(false);
  const inheritedParent = getFocusContext();
  const effectiveParent = $derived(parentFocusKey ?? inheritedParent);

  const navParams = $derived<SpatialNavParams>({
    focusKey,
    parentFocusKey: effectiveParent,
    focusable,
    autoFocus,
    trackChildren,
    saveLastFocusedChild,
    preferredChildFocusKey,
    isFocusBoundary,
    playSound,
    onEnterPress: (details) => {
      onEnterPress?.(details);
    },
    onArrowPress,
    onFocus: () => {
      isFocused = true;
      onFocus?.();
    },
    onBlur: () => {
      isFocused = false;
      onBlur?.();
    },
    onUpdateFocus: (focused) => {
      isFocused = focused;
    },
  });

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter' && onEnterPress) {
      e.preventDefault();
      onEnterPress();
    }
  }
</script>

<div
  {id}
  use:spatialNav={navParams}
  {tabIndex}
  {role}
  onkeydown={handleKeyDown}
  data-focus-key={focusKey}
  data-focused={isFocused ? 'true' : undefined}
  class="tv-no-select {className} {isFocused ? focusedClass : ''}"
>
  {#if children}
    {@render children({ focused: isFocused })}
  {/if}
</div>

// src/components/tv/Focusable.tsx
import { useEffect, type ReactNode, type KeyboardEvent } from 'react';
import { useFocusable } from '@noriginmedia/norigin-spatial-navigation';
import { classNames } from '@/utils/helpers';

interface FocusableProps {
  children: ReactNode;
  focusKey?: string;
  onEnterPress?: () => void;
  onArrowPress?: (direction: string, details: unknown) => boolean;
  onFocus?: () => void;
  className?: string;
  focusedClassName?: string;
  autoFocus?: boolean;
  trackChildren?: boolean;
  saveLastFocusedChild?: boolean;
  preferredChildFocusKey?: string;
  focusable?: boolean;
  tabIndex?: number;
}

export function Focusable({
  children,
  focusKey,
  onEnterPress,
  onArrowPress,
  onFocus,
  className,
  focusedClassName,
  autoFocus = false,
  trackChildren = false,
  saveLastFocusedChild = false,
  preferredChildFocusKey,
  focusable = true,
  tabIndex = 0,
}: FocusableProps) {
  const { focusKey: resolvedKey, ref, focused, focusSelf } = useFocusable({
    focusKey,
    focusable,
    onEnterPress: onEnterPress ? () => { onEnterPress(); } : undefined,
    onArrowPress: onArrowPress ? (direction, _props, details) => onArrowPress(direction, details) : undefined,
    onFocus: onFocus ? () => { onFocus(); } : undefined,
    trackChildren,
    saveLastFocusedChild,
    preferredChildFocusKey,
  });

  useEffect(() => {
    if (autoFocus) {
      focusSelf();
    }
  }, [autoFocus, focusSelf]);

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Enter' && onEnterPress) {
      e.preventDefault();
      onEnterPress();
    }
  };

  return (
    <div
      ref={ref as React.RefObject<HTMLDivElement>}
      tabIndex={tabIndex}
      role="button"
      onKeyDown={handleKeyDown}
      data-focus-key={resolvedKey}
      data-focused={focused}
      className={classNames(
        'tv-no-select',
        focused && focusedClassName,
        className,
      )}
    >
      {children}
    </div>
  );
}
