// src/App.tsx
import { useEffect, useState } from 'react';
import { RouterProvider, createHashRouter, createBrowserRouter, Navigate } from 'react-router-dom';
import { router } from '@/router';
import { useAuthStore } from '@/stores/authStore';
import { useConfigStore } from '@/stores/configStore';
import { useSiteSettingsStore } from '@/stores/siteSettingsStore';
import { TVToast } from '@/components/ui/TVToast';
import { useToastStore } from '@/stores/toastStore';
import { checkCompat } from '@/services/compat';
import { IncompatibleBrowserScreen } from '@/components/ui/IncompatibleBrowserScreen';
import { useNativeBridgeSync } from '@/hooks/useNativeBridgeSync';
import { checkGeoBlock } from '@/services/geoblocking';
import { GeoBlockedLayout } from '@/components/layout/GeoBlockedLayout';
import { LiveTVScreen } from '@/pages/LiveTVScreen';
import { OverlayPanelHost } from '@/components/overlay/OverlayPanelHost';
import { IS_DEV } from '@/stores/configStore';
import { CinelarLogo } from "./components/ui/CinelarLogo";

// Initialize stores immediately at module load time
useAuthStore.getState().initialize();
useConfigStore.getState().loadConfig();

const compatResult = checkCompat();

const createRouterFunction = IS_DEV ? createBrowserRouter : createHashRouter;

const geoBlockedRouter = createRouterFunction([
  {
    element: <GeoBlockedLayout />,
    children: [
      {
        path: '/live',
        element: <LiveTVScreen />,
      },
      {
        path: '*',
        element: <Navigate to="/live" replace />,
      },
    ],
  },
]);

let betaToastShown = false;

export default function App() {
  const isReady = useAuthStore((s) => s.isReady);
  const configLoaded = useConfigStore((s) => s.isLoaded);
  const [geoBlocked, setGeoBlocked] = useState(false);
  const [geoCheckDone, setGeoCheckDone] = useState(false);
  useNativeBridgeSync();

  useEffect(() => {
    if (!configLoaded) return;
    let mounted = true;
    (async () => {
      try {
        const geo = await checkGeoBlock();
        if (mounted) setGeoBlocked(geo.blocked);
      } catch (err) {
        console.warn('checkGeoBlock failed', err);
      } finally {
        if (mounted) setGeoCheckDone(true);
      }
    })();
    return () => { mounted = false; };
  }, [configLoaded]);

  // Load site settings once config is ready (non-blocking, non-critical)
  useEffect(() => {
    if (!configLoaded) return;
    useSiteSettingsStore.getState().loadSettings();
  }, [configLoaded]);

  useEffect(() => {
    if (!isReady || betaToastShown) return;
    betaToastShown = true;
    useToastStore.getState().show('Gracias por probar la beta', 'info', 5000);
  }, [isReady]);

  if (!compatResult.compatible) {
    return <IncompatibleBrowserScreen result={compatResult} />;
  }

  if (geoBlocked) {
    return (
      <>
        <RouterProvider router={geoBlockedRouter} />
        <OverlayPanelHost />
        <TVToast />
      </>
    );
  }


  if (!isReady || !geoCheckDone) {
    return (
      <div className="w-full h-full flex items-center justify-center bg-bg">
        <CinelarLogo
          className="w-[clamp(180px,32vw,280px)] h-auto"
        />

      </div>
    );
  }



  return (
    <>
      <RouterProvider router={router} />
      <OverlayPanelHost />
      <TVToast />
    </>
  );
}

// src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Router, { push } from 'svelte-spa-router';
  import type { RouteDetail } from 'svelte-spa-router';
  import { routes, geoBlockedRoutes } from '@/router/routes';
  import { authStore } from '@/stores/authStore';
  import { configStore } from '@/stores/configStore';
  import { siteSettingsStore } from '@/stores/siteSettingsStore';
  import { toastStore } from '@/stores/toastStore';
  import { checkCompat } from '@/services/compat';
  import { checkGeoBlock } from '@/services/geoblocking';
  import { initNativeBridgeSync } from '@/services/nativeBridgeSync';
  import { initSpatialNavigation } from '@/lib/spatial/init';
  import TVToast from '@/components/ui/TVToast.svelte';
  import OverlayPanelHost from '@/components/overlay/OverlayPanelHost.svelte';
  import IncompatibleBrowserScreen from '@/components/ui/IncompatibleBrowserScreen.svelte';
  import CinelarLogo from '@/components/ui/CinelarLogo.svelte';
  import GeoBlockedLayout from '@/components/layout/GeoBlockedLayout.svelte';

  // ── Compat check (sync, before anything renders) ────────────────────────────
  const compatResult = checkCompat();

  // ── State ────────────────────────────────────────────────────────────────────
  let geoBlocked = $state(false);
  let geoCheckDone = $state(false);
  let betaToastShown = false;

  // ── Derived from stores ──────────────────────────────────────────────────────
  const authState = $derived(authStore.getState());
  let isReady = $state(authStore.getState().isReady);
  let configLoaded = $state(configStore.getState().isLoaded);

  onMount(() => {
    // Subscribe to store changes
    const unsubAuth = authStore.subscribe((s) => {
      isReady = s.isReady;
    });

    const unsubConfig = configStore.subscribe((s) => {
      configLoaded = s.isLoaded;
    });

    // Native bridge sync
    const unsubBridge = initNativeBridgeSync();

    // Spatial navigation
    initSpatialNavigation();

    return () => {
      unsubAuth();
      unsubConfig();
      unsubBridge();
    };
  });

  // ── Geo-block check (runs once config is loaded) ────────────────────────────
  $effect(() => {
    if (!configLoaded) return;

    let mounted = true;
    (async () => {
      try {
        const geo = await checkGeoBlock();
        if (mounted) geoBlocked = geo.blocked;
      } catch (err) {
        console.warn('checkGeoBlock failed', err);
      } finally {
        if (mounted) geoCheckDone = true;
      }
    })();

    return () => { mounted = false; };
  });

  // ── Site settings (non-blocking) ─────────────────────────────────────────────
  $effect(() => {
    if (!configLoaded) return;
    siteSettingsStore.getState().loadSettings();
  });

  // ── Beta toast ───────────────────────────────────────────────────────────────
  $effect(() => {
    if (!isReady || betaToastShown) return;
    betaToastShown = true;
    toastStore.getState().show('Gracias por probar la beta', 'info', 5000);
  });

  // ── Route guard: redirect on conditionsFailed ─────────────────────────────
  function conditionsFailed(detail: RouteDetail) {
    const path: string = detail?.location ?? '/';
    const state = authStore.getState();
    if (!state.isAuthenticated && !state.isGuest) {
      push('/auth');
    } else if (state.isAuthenticated && !state.selectedProfile) {
      push('/select-profile');
    } else {
      push('/home');
    }
  }
</script>

{#if !compatResult.compatible}
  <IncompatibleBrowserScreen result={compatResult} />
{:else if geoBlocked}
  <GeoBlockedLayout>
    <Router routes={geoBlockedRoutes} onConditionsFailed={conditionsFailed} />
  </GeoBlockedLayout>
  <OverlayPanelHost />
  <TVToast />
{:else if !isReady || !geoCheckDone}
  <div class="splash">
    <CinelarLogo class="logo" />
  </div>
{:else}
  <Router {routes} onConditionsFailed={conditionsFailed} />
  <OverlayPanelHost />
  <TVToast />
{/if}

<style>
  .splash {
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    background: var(--color-bg, #0a0a0f);
  }

  .splash :global(.logo) {
    width: clamp(180px, 32vw, 280px);
    height: auto;
  }
</style>
